INSERT INTO STUDENTS(first_name, last_name) VALUES('Sabrina-Maria', 'Sakka')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Ilaha', 'Behbudova')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Nuraddin', 'Sadili')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Emil', 'Huseynov')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Huseyn', 'Jabbarov')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Kanan', 'Gafarov')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Ali', 'Aliyev')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Rufat', 'Hajiyev')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Laman', 'Asgarova')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Fidan', 'Aliyeva')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Yusif', 'Yusifli')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Fikrat', 'Pashazada')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Samir', 'Mammadzada')
INSERT INTO STUDENTS(first_name, last_name) VALUES('Ilaha', 'Mammadzada')

INSERT INTO COURSES(name, description, credits) VALUES('WM1', 'Web and Mobile 1', 6)
INSERT INTO COURSES(name, description, credits) VALUES('WM2', 'Web and Mobile 2', 6)
INSERT INTO COURSES(name, description, credits) VALUES('PP1', 'Programming Principles 1', 6)
INSERT INTO COURSES(name, description, credits) VALUES('PP2', 'Programming Principles 2', 6)
INSERT INTO COURSES(name, description, credits) VALUES('DB1', 'Database Fundamentals', 6)
INSERT INTO COURSES(name, description, credits) VALUES('ICT', 'Introduction to ICT', 6)

INSERT INTO student_course VALUES(2, 2)
INSERT INTO student_course VALUES(2, 5)
INSERT INTO student_course VALUES(1, 1)
INSERT INTO student_course VALUES(1, 4)
INSERT INTO student_course VALUES(1, 3)
INSERT INTO student_course VALUES(4, 2)
INSERT INTO student_course VALUES(4, 3)
INSERT INTO student_course VALUES(4, 5)
INSERT INTO student_course VALUES(6, 2)
INSERT INTO student_course VALUES(7, 3)
INSERT INTO student_course VALUES(9, 5)

