INSERT INTO ATTENDEES(first_name, last_name) VALUES('Sabrina-Maria', 'Sakka')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Ilaha', 'Behbudova')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Nuraddin', 'Sadili')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Emil', 'Huseynov')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Huseyn', 'Jabbarov')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Kanan', 'Gafarov')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Ali', 'Aliyev')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Rufat', 'Hajiyev')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Laman', 'Asgarova')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Fidan', 'Aliyeva')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Yusif', 'Yusifli')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Fikrat', 'Pashazada')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Samir', 'Mammadzada')
INSERT INTO ATTENDEES(first_name, last_name) VALUES('Ilaha', 'Mammadzada')

INSERT INTO EVENTS(name, description) VALUES('Music Festival', 'a multi-day event featuring different artists, genres of music, and various stages')
INSERT INTO EVENTS(name, description) VALUES('Sports Competition', 'a tournament or a series of matches featuring different teams and players in a particular sport')
INSERT INTO EVENTS(name, description) VALUES('Conference', 'a gathering of people to discuss a particular topic, industry or field. It could feature keynote speakers, workshops, and breakout sessions')
INSERT INTO EVENTS(name, description) VALUES('Art Exhibition', 'a display of art pieces from various artists in a particular medium, such as paintings, sculptures, or photography')
INSERT INTO EVENTS(name, description) VALUES('Charity Gala', 'an event to raise funds and awareness for a particular cause, featuring live entertainment, auctions, and speeches from keynote speakers')
INSERT INTO EVENTS(name, description) VALUES('Trade Show', 'an event where different companies showcase their products and services in a particular industry or field')

INSERT INTO attendee_event VALUES(2, 2)
INSERT INTO attendee_event VALUES(2, 5)
INSERT INTO attendee_event VALUES(1, 1)
INSERT INTO attendee_event VALUES(1, 4)
INSERT INTO attendee_event VALUES(1, 3)
INSERT INTO attendee_event VALUES(4, 2)
INSERT INTO attendee_event VALUES(4, 3)
INSERT INTO attendee_event VALUES(4, 5)
INSERT INTO attendee_event VALUES(6, 2)
INSERT INTO attendee_event VALUES(7, 3)
INSERT INTO attendee_event VALUES(9, 5)
